title: Hello, world! I'm Weibo
description: > # this means to ignore newlines until "baseurl:"
  This is an weibo blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog /flexible-jekyll
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Weibo # add your name
author-img: logo.jpg # add your photo
about-author: Feed in Weibo.  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:
social-linkedin: # add your Linkedin handle
social-email: yuliang@staff.weibo.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
